services:
  _defaults:
    autowire: true
    autoconfigure: true

  Aeliot\PhpCsFixerBaseline\:
    resource: '../src/*'
    exclude:
      - '../src/Console/Application.php'
      - '../src/Console/ContainerBuilder.php'
      - '../src/Dto'
      - '../src/Model'

  Aeliot\PhpCsFixerBaseline\Console\Command\:
    public: true
    resource: '../src/Console/Command/*'
    tags: ['console.command']
