name: TODO Registrar

on:
  push:
    branches: [ "main" ]

jobs:
  todo-registrar:
    name: Register TODO
    runs-on: ubuntu-latest

    # Define the permissions for the action
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Register TODOs
        uses: Aeliot-Tm/todo-registrar-action@1.6.5
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TODO_REGISTRAR_ACCESS_TOKEN }}
          GH_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
          GH_REPOSITORY_OWNER: ${{ vars.GITHUB_REPOSITORY_OWNER }}
        with:
          check_opened: 'true'
          config_path: scripts/todo-registrar/config.php
          env_vars: |
            GH_PERSONAL_ACCESS_TOKEN
            GH_REPOSITORY
            GH_REPOSITORY_OWNER
          new_branch_name: 'todo-registrar'
          user_email: 'action@github.com'
          user_name: 'GitHub Action'
